// .github/ai-ley/instructions/frameworks/examples/solid-js/example-6.tsx
import { createContext, useContext, createSignal, createMemo, JSX } from 'solid-js';
import { createStore, produce } from 'solid-js/store';

// User Store
interface UserState {
  users: User[];
  loading: boolean;
  error: string | null;
  selectedUser: User | null;
}

interface UserStore {
  state: UserState;
  actions: {
    fetchUsers: () => Promise<void>;
    addUser: (user: Omit<User, 'id'>) => void;
    updateUser: (id: number, updates: Partial<User>) => void;
    deleteUser: (id: number) => void;
    selectUser: (user: User | null) => void;
    clearError: () => void;
  };
}

const UserContext = createContext<UserStore>();

export const UserProvider = (props: { children: JSX.Element }) => {
  const [state, setState] = createStore<UserState>({
    users: [],
    loading: false,
    error: null,
    selectedUser: null
  });
  
  const actions = {
    fetchUsers: async () => {
      setState('loading', true);
      setState('error', null);
      
      try {
        const response = await fetch('/api/users');
        if (!response.ok) throw new Error('Failed to fetch users');
        
        const users = await response.json();
        setState('users', users);
      } catch (error) {
        setState('error', error instanceof Error ? error.message : 'Unknown error');
      } finally {
        setState('loading', false);
      }
    },
    
    addUser: (userData: Omit<User, 'id'>) => {
      const newUser: User = {
        ...userData,
        id: Date.now() // Simple ID generation
      };
      
      setState('users', users => [...users, newUser]);
    },
    
    updateUser: (id: number, updates: Partial<User>) => {
      setState('users', 
        produce(users => {
          const userIndex = users.findIndex(u => u.id === id);
          if (userIndex !== -1) {
            Object.assign(users[userIndex], updates);
          }
        })
      );
    },
    
    deleteUser: (id: number) => {
      setState('users', users => users.filter(u => u.id !== id));
      
      // Clear selection if deleted user was selected
      if (state.selectedUser?.id === id) {
        setState('selectedUser', null);
      }
    },
    
    selectUser: (user: User | null) => {
      setState('selectedUser', user);
    },
    
    clearError: () => {
      setState('error', null);
    }
  };
  
  const store: UserStore = { state, actions };
  
  return (
    <UserContext.Provider value={store}>
      {props.children}
    </UserContext.Provider>
  );
};

export const useUserStore = () => {
  const context = useContext(UserContext);
  if (!context) {
    throw new Error('useUserStore must be used within UserProvider');
  }
  return context;
};

// App State Store (Global)
interface AppState {
  theme: 'light' | 'dark';
  sidebarOpen: boolean;
  notifications: Notification[];
}

interface Notification {
  id: string;
  type: 'success' | 'error' | 'warning' | 'info';
  message: string;
  duration?: number;
}

export const createAppStore = () => {
  const [state, setState] = createStore<AppState>({
    theme: 'light',
    sidebarOpen: false,
    notifications: []
  });
  
  const toggleTheme = () => {
    setState('theme', theme => theme === 'light' ? 'dark' : 'light');
  };
  
  const toggleSidebar = () => {
    setState('sidebarOpen', open => !open);
  };
  
  const addNotification = (notification: Omit<Notification, 'id'>) => {
    const id = crypto.randomUUID();
    const newNotification = { ...notification, id };
    
    setState('notifications', notifications => [...notifications, newNotification]);
    
    // Auto-remove after duration
    if (notification.duration) {
      setTimeout(() => {
        removeNotification(id);
      }, notification.duration);
    }
  };
  
  const removeNotification = (id: string) => {
    setState('notifications', notifications => 
      notifications.filter(n => n.id !== id)
    );
  };
  
  return {
    state,
    toggleTheme,
    toggleSidebar,
    addNotification,
    removeNotification
  };
};

// .github/ai-ley/instructions/frameworks/examples/qwik/example-6.tsx
import { 
  component$, 
  createContextId, 
  useContextProvider, 
  useContext, 
  useStore, 
  $, 
  Slot 
} from '@builder.io/qwik';

// User context and store
interface User {
  id: number;
  name: string;
  email: string;
  avatar?: string;
}

interface UserStore {
  users: User[];
  loading: boolean;
  error: string | null;
  selectedUser: User | null;
}

export const UserContext = createContextId<UserStore>('user-context');

// User Provider Component
export const UserProvider = component$(() => {
  const userStore = useStore<UserStore>({
    users: [],
    loading: false,
    error: null,
    selectedUser: null
  });
  
  useContextProvider(UserContext, userStore);
  
  return <Slot />;
});

// User Actions (Custom Hook Pattern)
export const useUserActions = () => {
  const store = useContext(UserContext);
  
  const fetchUsers = $(async () => {
    store.loading = true;
    store.error = null;
    
    try {
      const response = await fetch('/api/users');
      if (!response.ok) throw new Error('Failed to fetch users');
      
      const users = await response.json();
      store.users = users;
    } catch (error) {
      store.error = error instanceof Error ? error.message : 'Unknown error';
    } finally {
      store.loading = false;
    }
  });
  
  const addUser = $(async (userData: Omit<User, 'id'>) => {
    try {
      const response = await fetch('/api/users', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(userData)
      });
      
      if (!response.ok) throw new Error('Failed to add user');
      
      const newUser = await response.json();
      store.users = [...store.users, newUser];
    } catch (error) {
      store.error = error instanceof Error ? error.message : 'Failed to add user';
    }
  });
  
  const updateUser = $(async (id: number, updates: Partial<User>) => {
    try {
      const response = await fetch(`/api/users/${id}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(updates)
      });
      
      if (!response.ok) throw new Error('Failed to update user');
      
      const updatedUser = await response.json();
      store.users = store.users.map(user => 
        user.id === id ? updatedUser : user
      );
    } catch (error) {
      store.error = error instanceof Error ? error.message : 'Failed to update user';
    }
  });
  
  const deleteUser = $(async (id: number) => {
    try {
      const response = await fetch(`/api/users/${id}`, {
        method: 'DELETE'
      });
      
      if (!response.ok) throw new Error('Failed to delete user');
      
      store.users = store.users.filter(user => user.id !== id);
      
      if (store.selectedUser?.id === id) {
        store.selectedUser = null;
      }
    } catch (error) {
      store.error = error instanceof Error ? error.message : 'Failed to delete user';
    }
  });
  
  const selectUser = $((user: User | null) => {
    store.selectedUser = user;
  });
  
  return {
    fetchUsers,
    addUser,
    updateUser,
    deleteUser,
    selectUser
  };
};

// Component using the store
export const UserList = component$(() => {
  const store = useContext(UserContext);
  const { fetchUsers, deleteUser, selectUser } = useUserActions();
  
  // Fetch users on component mount
  useOnDocument('DOMContentLoaded', fetchUsers);
  
  return (
    <div class="user-list">
      <h2>Users ({store.users.length})</h2>
      
      {store.loading && <div class="loading">Loading users...</div>}
      
      {store.error && (
        <div class="error">
          Error: {store.error}
        </div>
      )}
      
      <div class="users-grid">
        {store.users.map((user) => (
          <div key={user.id} class="user-card">
            <h3>{user.name}</h3>
            <p>{user.email}</p>
            
            <div class="user-actions">
              <button onClick$={() => selectUser(user)}>
                Select
              </button>
              <button 
                onClick$={() => deleteUser(user.id)}
                class="delete-btn"
              >
                Delete
              </button>
            </div>
          </div>
        ))}
      </div>
      
      {store.selectedUser && (
        <div class="selected-user">
          <h3>Selected User:</h3>
          <p>{store.selectedUser.name}</p>
        </div>
      )}
    </div>
  );
});
